### PR TITLE
Changed "yea" to "yay"

### PR DESCRIPTION
**Pull request by Blindripper**

### CODE REVIEW

**Comment by 3noch** [comment]
Did `yea` not work for you? It is the correct spelling and future version of tezos-client will use it over "yay".

**Comment by Blindripper** [comment]
Didn't test it. But "yay" is what tezos-client man says. Also the "voting.rst" from Tezos GitLab contains both expressions. I thought it would be useful to align everything. To not confuse Users.

**Comment by Blindripper** [comment]
Maybe we should change it in general to "Yes" and "No".

**Comment by 3noch** [comment]
I agree with alignment but the misspelling is also confusing ("Did they typo that?") so I'd rather hold out for the hopeful future that we all align on correct spellings. :P I think we can get `tezos-client` to show the correct spelling in the man page.

**Pull request closed without merging**
