### PR TITLE
Remove syntax error in src/types.h

### PR DESCRIPTION
**Pull request by matthewbauer**
This looks like an error, unsure why it doesn't result in a compiler error in the current setup.

### CODE REVIEW

**Comment by 3noch** [comment]
`_Static_assert` ignores it's second argument in our compiler. I don't know why. But good catch.

**Comment by 3noch** [comment]
@matthewbauer BTW, you need to rebase and sign every commit to this repo or it will be rejected.

**Comment by matthewbauer** [comment]
> @matthewbauer BTW, you need to sign every commit to this repo or it will be rejected by GitHub. In this case you'll have to rebase/amend.

Yes! That should be fixable though. I think it has to do with using the glibc_multi headers here:

https://github.com/obsidiansystems/ledger-app-tezos/blob/master/nix/fhs.nix#L20

**Comment by 3noch** [comment]
Could be! I don't know if those are required by the SDK or not...

**Pull request merged**
